name: build movie service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build
        id: docker-build
        run: |
          docker build . -t dandonghukim/helidon-movie-api-mp:${{ github.sha }}
      - name: docker push
        id: docker-push
        run: |
          docker push dandonghukim/helidon-movie-api-mp:${{ github.sha }}
      - name: Checkout K8s Manifest
        uses: actions/checkout@v4
        with:
          repository: donghukim2023/movie-k8s-manifest-repo
          path: production
          token: ${{ secrets.GIT_REPOPAT }}
      - name: Change config repo manifest
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers.[0].image = "dandonghukim/helidon-movie-api-mp:${{ github.sha }}"' kube-helidon-movie-api-mp-deployment.yml
      - name: Pushes to config repository
        run: |
          git add .
          git config --global user.email "dan.donghu.kim@gmail.com"
          git config --global user.name "donghukim2023"
          git commit -am "..Change Image version to ${{ github.sha }}"
          git push
